title: HobdayLab
email: claire.hobday@ed.ac.uk
description: HobdayLab â€“ School of Chemistry, University of Edinburgh
baseurl: ""
url: ""
markdown: kramdown
collections:
  people:
    output: true
  projects:
    output: true
